### ISSUE TITLE
v1.0.1 - Brightness is not restored

### ISSUE THREAD

**Issue by gtirloni** [siddharthkp/rest-your-eyes#1]
**Environment:**

Fedora 25 (kernel 4.8.11)
Node: 6.9.1

How to reproduce:

    $ rest ls

**Results:**

Brightness continues at zero after command finishes (has to be restored manually)

**Expected Results:**

Brightness is restored to original value.

**Comment by siddharthkp** [comment]
@gtirloni Thanks for reporting!

Can your confirm the brightness module works on Fedora: https://github.com/kevva/brightness#usage

**Comment by gtirloni** [comment]
It works, with a small workaround. I had to set this device to o=rw so my user could write to it:

    /sys/class/backlight/intel_backlight/brightness

Result from brightness' test code:

```$ node test-brightness.js 
Changed brightness to 80%
0.7993596584845251
```

**Comment by siddharthkp** [comment]
Can I do something from the lib to handle this?

**Comment by gtirloni** [comment]
That device is owned by root:root, but I can change the brightness just fine from KDE. I'll do some digging later today and I'll let you know. Thanks for this tool, it's a pretty nice idea.
